# Generated by Django 3.0.8 on 2020-07-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
